---
- name: Listen for OCP Virt Events
  hosts: all
  sources:
    - sabre1041.eda.k8s:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        api_key: "{{ ocp_bearer_token }}"
        host: "{{ ocp_api_endpoint }}"
        verify_ssl: false
  rules:
    - name: Print Event
      condition: event.meta is defined
      action:
        debug:      
          var: event 
          
    - name: Alert when Created 
      condition: event.resource.status.printableStatus == "Provisioning" 
      action:
        debug:  
          msg: "{{ event.resource.metadata.name }} Created"

    - name: Alert when Running 
      condition: event.resource.status.printableStatus == "Running"
      action:
        debug: 
          msg: "{{ event.resource.metadata.name }} is now Running"