---
- name: Listen for OCP Virt Events
  hosts: all
  sources:
    - sabre1041.eda.k8s:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        api_key: "{{ ocp_bearer_token }}"
        host: "{{ ocp_api_endpoint }}"
        verify_ssl: false
  rules:
    - name: Print Event
      condition: event.meta is defined
      action:
        debug:      