---
- name: Listen for events on a webhook
  hosts: all
  ## Define our source for events
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5005
  ## Define the conditions we are looking for
  rules:
    - name: Say Hello
      condition: event.payload.name == "Jerry"
  ## Define the action we should take should the condition be met
      actions:
        - debug:
        - run_playbook:
            name: playbooks/webhook_response.yml