--- 
- name: Actions for OCP Virt VM Running Event 
  hosts: "{{ target | default('localhost') }}"
  gather_facts: no 

  tasks:
    - name: Print out event details 
      ansible.builtin.debug:
        var: ansible_eda 